AuthNET.Sharing.WebApp/Controllers/ExternalController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AuthNET.Sharing.WebApp.Controllers
{
    [AllowAnonymous]
    public class ExternalController : Controller
    {
        public ExternalController()
        {
        }

        /// <summary>
        /// Initiate roundtrip to external authentication provider
        /// </summary>
        [HttpGet]
        public IActionResult Challenge(string scheme, string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl)) returnUrl = "~/";

            if (!Url.IsLocalUrl(returnUrl))
            {
                // user might have clicked on a malicious link - should be logged
                throw new Exception("invalid return URL");
            }

            // start challenge and roundtrip the return URL and scheme 
            var props = new AuthenticationProperties
            {
                RedirectUri = Url.Action(nameof(Callback)),
                Items =
                {
                    { "returnUrl", returnUrl },
                    { "scheme", scheme },
                }
            };

            return Challenge(props, scheme);
        }

        /// <summary>
        /// Post processing of external authentication
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Callback()
        {
            // read external identity from the temporary cookie
            var result = await HttpContext.AuthenticateAsync(AuthConstants.AuthenticationSchemes.ExternalCookies);
            if (result?.Succeeded != true)
            {
                throw new Exception("External authentication error");
            }

            // retrieve return URL
            var returnUrl = result.Properties.Items["returnUrl"] ?? "~/";

            // [Important] demo only, need to use Identity federation and user provisioning instead
            var externalUser = result.Principal;
            var userIdClaim = externalUser.FindFirst(AuthConstants.AppClaimTypes.Subject) ??
                              externalUser.FindFirst(ClaimTypes.NameIdentifier) ??
                              throw new Exception("Unknown userid");

            // remove the user id claim so we don't include it as an extra claim if/when we provision the user
            var claims = externalUser.Claims.ToList();
            claims.Remove(userIdClaim);

            var provider = result.Properties.Items["scheme"];
            var providerUserId = userIdClaim.Value;
            var userClaims = TransformExternalClaims(provider, claims);

            var claimsIdentity = new ClaimsIdentity(userClaims, CookieAuthenticationDefaults.AuthenticationScheme);
            claimsIdentity.AddClaim(new Claim(ClaimTypes.Name, providerUserId));

            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

            await HttpContext.SignInAsync(claimsPrincipal);
            // delete temporary cookie used during external authentication
            await HttpContext.SignOutAsync(AuthConstants.AuthenticationSchemes.ExternalCookies);

            return Redirect(returnUrl);
        }

        private IEnumerable<Claim> TransformExternalClaims(string provider, IEnumerable<Claim> claims)
        {
            string email, name, givenName, familyName;

            switch (provider)
            {
                case AuthConstants.AuthenticationSchemes.Facebook:
                    email = claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
                    name = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
                    givenName = claims.FirstOrDefault(c => c.Type == ClaimTypes.GivenName)?.Value;
                    familyName = claims.FirstOrDefault(c => c.Type == ClaimTypes.Surname)?.Value;
                    break;
                case AuthConstants.AuthenticationSchemes.Google:
                    email = claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
                    name = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
                    givenName = claims.FirstOrDefault(c => c.Type == ClaimTypes.GivenName)?.Value;
                    familyName = claims.FirstOrDefault(c => c.Type == ClaimTypes.Surname)?.Value;
                    break;
                default:
                    throw new NotSupportedException();
            }

            var userClaims = new List<Claim>()
            {
                new Claim(ClaimTypes.Email, email),
            };

            if (givenName != null)
            {
                userClaims.AddRange(new[]
                {
                    new Claim(ClaimTypes.GivenName, givenName),
                    new Claim(ClaimTypes.Surname, familyName)
                });
            }

            return userClaims;
        }
    }
}

AuthNET.Sharing.WebApp/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AuthNET.Sharing.WebApp.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AuthNET.Sharing.WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace AuthNET.Sharing.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AuthNET.Sharing.WebApp/Pages/Index.cshtml.cs
using AuthNET.Sharing.WebApp.Models;
using AuthNET.Sharing.WebApp.Persistence;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace AuthNET.Sharing.WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly DataContext _dataContext;
        private readonly IMapper _mapper;

        public IndexModel(ILogger<IndexModel> logger,
            DataContext dataContext,
            IMapper mapper)
        {
            _logger = logger;
            _dataContext = dataContext;
            _mapper = mapper;
        }

        public IEnumerable<UserClaimModel> UserClaims { get; set; }
        public AppUserModel UserInfo { get; set; }
        public string UserInfoSerialized { get; set; }

        public void OnGet()
        {
            UserClaims = User.Claims.Select(claim => new UserClaimModel
            {
                Type = claim.Type,
                Value = claim.Value
            }).ToArray();

            UserInfo = _dataContext.Users.Where(user => user.Id == User.Identity.Name)
                .ProjectTo<AppUserModel>(_mapper.ConfigurationProvider)
                .FirstOrDefault();

            if (UserInfo != null)
                UserInfoSerialized = JsonConvert.SerializeObject(UserInfo, Formatting.Indented);
            else UserInfoSerialized = "User is not in database yet";
        }
    }

    public class UserClaimModel
    {
        public string Type { get; set; }
        public string Value { get; set; }
    }
}

AuthNET.Sharing.WebApp/Pages/Login.cshtml.cs
using AuthNET.Sharing.WebApp.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace AuthNET.Sharing.WebApp.Pages
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly IIdentityService _identityService;

        public LoginModel(IIdentityService identityService)
        {
            _identityService = identityService;
        }

        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; }

        public IEnumerable<ExternalProvider> ExternalProviders => new[]
        {
            new ExternalProvider { AuthenticationScheme = AuthConstants.AuthenticationSchemes.Facebook },
            new ExternalProvider { AuthenticationScheme = AuthConstants.AuthenticationSchemes.Google }
        };

        [BindProperty]
        public LoginInputViewModel Input { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
                return Page();

            var user = await _identityService.AuthenticateAsync(Input.Username, Input.Password);

            if (user == null)
            {
                ModelState.AddModelError("", "Invalid username or password");
                return Page();
            }

            AuthenticationProperties props = null;
            if (Input.RememberLogin)
            {
                props = new AuthenticationProperties
                {
                    IsPersistent = true,
                    ExpiresUtc = DateTimeOffset.UtcNow.AddDays(7)
                };
            };

            var claimsPrincipal = await _identityService
                .GetUserPrincipalAsync(user, CookieAuthenticationDefaults.AuthenticationScheme);

            // [Important] since Cookies is default, we don't need to specify it explicitly 
            //await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal, props);
            await HttpContext.SignInAsync(claimsPrincipal, props);

            if (Url.IsLocalUrl(ReturnUrl))
            {
                return Redirect(ReturnUrl);
            }
            else
            {
                // user might have clicked on a malicious link - should be logged
                throw new Exception("invalid return URL");
            }
        }
    }

    public class LoginInputViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public bool RememberLogin { get; set; }
    }

    public class ExternalProvider
    {
        public string AuthenticationScheme { get; set; }
        public string DisplayName => AuthenticationScheme;
    }
}

AuthNET.Sharing.WebApp/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace AuthNET.Sharing.WebApp.Pages
{
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnGet(string returnUrl)
        {
            if (returnUrl != null && !Url.IsLocalUrl(returnUrl)) return BadRequest();

            //await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync();

            if (returnUrl == null) return LocalRedirect("/");

            return new EmptyResult();
        }
    }
}

AuthNET.Sharing.WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AuthNET.Sharing.WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AuthNET.Sharing.WebApp/Pages/AccessDenied.cshtml
@page
@model AuthNET.Sharing.WebApp.Pages.AccessDeniedModel
@{
}

<div class="text-center">
    <h1 class="display-4 text-danger">Access Denied</h1>
</div>

AuthNET.Sharing.WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<div class="container">
    <h4>USER INFO</h4>
    <pre>@Model.UserInfoSerialized</pre>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead class="thead-light">
                    <tr class="d-table-row">
                        <th class="d-table-cell">Type</th>
                        <th class="d-table-cell">Value</th>
                    </tr>
                </thead>
                <tbody class="">
                    @foreach (var item in Model.UserClaims)
                    {
                        <tr class="d-table-row">
                            <td class="d-table-cell">@item.Type</td>
                            <td class="d-table-cell">@item.Value</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

AuthNET.Sharing.WebApp/Pages/Login.cshtml
@page
@model AuthNET.Sharing.WebApp.Pages.LoginModel
@{
}

<div class="login-page">
    <div class="lead">
        <h1>Login</h1>
        <p>Choose how to login</p>
    </div>

    <partial name="_ValidationSummary" />

    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h2>Local Account</h2>
                </div>

                <div class="card-body">
                    <form method="post">
                        <input type="hidden" asp-for="ReturnUrl" />

                        <div class="form-group">
                            <label asp-for="Input.Username"></label>
                            <input class="form-control" placeholder="Username" asp-for="Input.Username" autofocus>
                        </div>
                        <div class="form-group">
                            <label asp-for="Input.Password"></label>
                            <input class="form-control" placeholder="Password" asp-for="Input.Password" autocomplete="off">
                        </div>

                        <div class="form-group">
                            <div class="form-check">
                                <input class="form-check-input" asp-for="Input.RememberLogin">
                                <label class="form-check-label" asp-for="Input.RememberLogin">
                                    Remember My Login
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <a asp-action="ResetPassword"
                               asp-controller="Account">
                                Forget your password? Click here to reset!
                            </a>
                        </div>

                        <div class="form-group">
                            <a asp-action="Register"
                               asp-controller="Account"
                               asp-route-returnUrl="@Model.ReturnUrl">
                                Not register yet? Click here!
                            </a>
                        </div>

                        <button class="btn btn-primary" name="button" value="login">Login</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h2>External Account</h2>
                </div>
                <div class="card-body">
                    <ul class="list-inline">
                        @foreach (var provider in Model.ExternalProviders)
                        {
                            <li class="list-inline-item">
                                <a class="btn btn-secondary"
                                   asp-controller="External"
                                   asp-action="Challenge"
                                   asp-route-scheme="@provider.AuthenticationScheme"
                                   asp-route-returnUrl="@Model.ReturnUrl">
                                    @provider.DisplayName
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

AuthNET.Sharing.WebApp/Pages/Logout.cshtml
@page
@model AuthNET.Sharing.WebApp.Pages.LogoutModel
@{
}